namespace: staging

replicaCount: 2

image:
  repository: 075120018043.dkr.ecr.us-east-1.amazonaws.com/color-app
  pullPolicy: IfNotPresent
  tag: "v1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "color-app"

podAnnotations: {}
podLabels: {}

lbService:
  port: 80
  targetPort: 8080
  annotations:
    type: "external"
    targetType: "ip"
    scheme: "internet-facing"


resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

configmap:
  APP_COLOR: "yellow"
  APP_ENV: "staging"
  APP_MESSAGE: "Hello from Staging!"


volume:
  accessMode: ReadWriteOnce
  storageClass: gp2
  size: 1Gi

externalSecret:
  region: us-east-1
  serviceAccountName: eso-sa
  refreshInterval: 1m
  remoteKey: color-app/stg
  keys:
  - name: SECRET_KEY
  - name: DB_PASSWORD
  - name: API_KEY

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
