apiVersion: v1
kind: Secret
metadata:
  name: wandaprep-tls-secret
type: Opaque
data:
  api-key: d2FuZGFwcmVwLWFwaS1rZXktMjAyNA==
---
apiVersion: v1
kind: Pod
metadata:
  name: wandaprep-secret-volume
  labels:
    app: wandaprep
spec:
  containers:
  - name: wandaprep-container
    image: chafah/wandaprep:v1.0
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: secret-volume
      mountPath: /usr/src/app/secrets
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: wandaprep-tls-secret
