kind: Service
apiVersion: v1
metadata:
  name: multicolor-app-svc
spec:
  selector:
    name: multicolor-app
  type: NodePort
  ports:
  - name:  tcp
    port:  80
    targetPort:  8080
    nodePort: 31200