apiVersion: v1
kind: Pod
metadata:
  name: wandaprep-app
  labels:
    app: wandaprep
spec:
  containers:
  - name: wandaprep-app-container
    image: chafah/wandaprep:v1.0
    ports:
    - containerPort: 8080
