apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "color-app.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "color-app.labels" . | nindent 4 }}
data:
  APP_COLOR: {{ .Values.configmap.APP_COLOR | quote }}
  APP_ENV: {{ .Values.configmap.APP_ENV | quote }}
  APP_MESSAGE: {{ .Values.configmap.APP_MESSAGE | quote }}
