apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "color-app.fullname" . }}-pvc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "color-app.labels" . | nindent 4 }}
spec:
  accessModes:
  - {{ .Values.volume.accessMode }}
  storageClassName: {{ .Values.volume.storageClass }}
  resources:
    requests:
      storage: {{ .Values.volume.size }}
