apiVersion: v1
kind: Secret
metadata:
  name: {{ include "color-app.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "color-app.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.secret.SECRET_KEY }}
